[repos."canac/budgeteer"]
prefix = "budgeteer"
init_command = "pnpm db:generate"

[repos."CruGlobal/conf-registration-web"]
prefix = "ert"
init_command = "yarn prepare"

[repos."CruGlobal/give-web"]
prefix = "give"

[repos."CruGlobal/mpdx-react"]
prefix = "mpdx"
init_command = "yarn gql"
