[tasks.setup]
run = [
  "overcommit --sign",
  "overcommit --install"
]

[tasks.gql]
run = "rails graphql:schema:idl"

[tasks.local-stage]
run = "dotenvx run --env-file .env.staging --"

[tools]
"dotenvx" = "latest"
